// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.3
// source: pensiero/v1/reasoning.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReasonerService_Entails_FullMethodName     = "/pensiero.v1.ReasonerService/Entails"
	ReasonerService_Contradicts_FullMethodName = "/pensiero.v1.ReasonerService/Contradicts"
	ReasonerService_Derive_FullMethodName      = "/pensiero.v1.ReasonerService/Derive"
	ReasonerService_Health_FullMethodName      = "/pensiero.v1.ReasonerService/Health"
)

// ReasonerServiceClient is the client API for ReasonerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ReasonerService exposes pensiero's symbolic reasoner over a topic graph so it
// can run as a separate process / on a different machine. Mirrors the
// reasoning.Reasoner contract a host application depends on.
type ReasonerServiceClient interface {
	// Entails decides whether a claim is symbolically supported, contradicted, or
	// unsupported, with the best supporting/conflicting proof.
	Entails(ctx context.Context, in *EntailsRequest, opts ...grpc.CallOption) (*EntailResult, error)
	// Contradicts reports an ontology-disjointness conflict for the claim.
	Contradicts(ctx context.Context, in *ContradictsRequest, opts ...grpc.CallOption) (*ContradictsResponse, error)
	// Derive returns ranked proof paths from Source toward Target (or any target).
	Derive(ctx context.Context, in *DeriveRequest, opts ...grpc.CallOption) (*DeriveResponse, error)
	// Health is a liveness probe.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type reasonerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReasonerServiceClient(cc grpc.ClientConnInterface) ReasonerServiceClient {
	return &reasonerServiceClient{cc}
}

func (c *reasonerServiceClient) Entails(ctx context.Context, in *EntailsRequest, opts ...grpc.CallOption) (*EntailResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntailResult)
	err := c.cc.Invoke(ctx, ReasonerService_Entails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reasonerServiceClient) Contradicts(ctx context.Context, in *ContradictsRequest, opts ...grpc.CallOption) (*ContradictsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContradictsResponse)
	err := c.cc.Invoke(ctx, ReasonerService_Contradicts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reasonerServiceClient) Derive(ctx context.Context, in *DeriveRequest, opts ...grpc.CallOption) (*DeriveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeriveResponse)
	err := c.cc.Invoke(ctx, ReasonerService_Derive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reasonerServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ReasonerService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReasonerServiceServer is the server API for ReasonerService service.
// All implementations must embed UnimplementedReasonerServiceServer
// for forward compatibility.
//
// ReasonerService exposes pensiero's symbolic reasoner over a topic graph so it
// can run as a separate process / on a different machine. Mirrors the
// reasoning.Reasoner contract a host application depends on.
type ReasonerServiceServer interface {
	// Entails decides whether a claim is symbolically supported, contradicted, or
	// unsupported, with the best supporting/conflicting proof.
	Entails(context.Context, *EntailsRequest) (*EntailResult, error)
	// Contradicts reports an ontology-disjointness conflict for the claim.
	Contradicts(context.Context, *ContradictsRequest) (*ContradictsResponse, error)
	// Derive returns ranked proof paths from Source toward Target (or any target).
	Derive(context.Context, *DeriveRequest) (*DeriveResponse, error)
	// Health is a liveness probe.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedReasonerServiceServer()
}

// UnimplementedReasonerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReasonerServiceServer struct{}

func (UnimplementedReasonerServiceServer) Entails(context.Context, *EntailsRequest) (*EntailResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Entails not implemented")
}
func (UnimplementedReasonerServiceServer) Contradicts(context.Context, *ContradictsRequest) (*ContradictsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Contradicts not implemented")
}
func (UnimplementedReasonerServiceServer) Derive(context.Context, *DeriveRequest) (*DeriveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Derive not implemented")
}
func (UnimplementedReasonerServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedReasonerServiceServer) mustEmbedUnimplementedReasonerServiceServer() {}
func (UnimplementedReasonerServiceServer) testEmbeddedByValue()                         {}

// UnsafeReasonerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReasonerServiceServer will
// result in compilation errors.
type UnsafeReasonerServiceServer interface {
	mustEmbedUnimplementedReasonerServiceServer()
}

func RegisterReasonerServiceServer(s grpc.ServiceRegistrar, srv ReasonerServiceServer) {
	// If the following call panics, it indicates UnimplementedReasonerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReasonerService_ServiceDesc, srv)
}

func _ReasonerService_Entails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReasonerServiceServer).Entails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReasonerService_Entails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReasonerServiceServer).Entails(ctx, req.(*EntailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReasonerService_Contradicts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContradictsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReasonerServiceServer).Contradicts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReasonerService_Contradicts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReasonerServiceServer).Contradicts(ctx, req.(*ContradictsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReasonerService_Derive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeriveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReasonerServiceServer).Derive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReasonerService_Derive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReasonerServiceServer).Derive(ctx, req.(*DeriveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReasonerService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReasonerServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReasonerService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReasonerServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReasonerService_ServiceDesc is the grpc.ServiceDesc for ReasonerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReasonerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pensiero.v1.ReasonerService",
	HandlerType: (*ReasonerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Entails",
			Handler:    _ReasonerService_Entails_Handler,
		},
		{
			MethodName: "Contradicts",
			Handler:    _ReasonerService_Contradicts_Handler,
		},
		{
			MethodName: "Derive",
			Handler:    _ReasonerService_Derive_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ReasonerService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pensiero/v1/reasoning.proto",
}
