// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: pensiero/v1/reasoning.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Claim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Predicate     string                 `protobuf:"bytes,2,opt,name=predicate,proto3" json:"predicate,omitempty"`
	Object        string                 `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Claim) Reset() {
	*x = Claim{}
	mi := &file_pensiero_v1_reasoning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Claim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claim) ProtoMessage() {}

func (x *Claim) ProtoReflect() protoreflect.Message {
	mi := &file_pensiero_v1_reasoning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Claim.ProtoReflect.Descriptor instead.
func (*Claim) Descriptor() ([]byte, []int) {
	return file_pensiero_v1_reasoning_proto_rawDescGZIP(), []int{0}
}

func (x *Claim) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Claim) GetPredicate() string {
	if x != nil {
		return x.Predicate
	}
	return ""
}

func (x *Claim) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

type ProofStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	Rule          string                 `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	Predicate     string                 `protobuf:"bytes,3,opt,name=predicate,proto3" json:"predicate,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	Confidence    float64                `protobuf:"fixed64,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProofStep) Reset() {
	*x = ProofStep{}
	mi := &file_pensiero_v1_reasoning_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProofStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProofStep) ProtoMessage() {}

func (x *ProofStep) ProtoReflect() protoreflect.Message {
	mi := &file_pensiero_v1_reasoning_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProofStep.ProtoReflect.Descriptor instead.
func (*ProofStep) Descriptor() ([]byte, []int) {
	return file_pensiero_v1_reasoning_proto_rawDescGZIP(), []int{1}
}

func (x *ProofStep) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *ProofStep) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *ProofStep) GetPredicate() string {
	if x != nil {
		return x.Predicate
	}
	return ""
}

func (x *ProofStep) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ProofStep) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ProofStep) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type Proof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Predicate     string                 `protobuf:"bytes,3,opt,name=predicate,proto3" json:"predicate,omitempty"`
	RuleClass     string                 `protobuf:"bytes,4,opt,name=rule_class,json=ruleClass,proto3" json:"rule_class,omitempty"`
	Steps         []*ProofStep           `protobuf:"bytes,5,rep,name=steps,proto3" json:"steps,omitempty"`
	Hops          int32                  `protobuf:"varint,6,opt,name=hops,proto3" json:"hops,omitempty"`
	Confidence    float64                `protobuf:"fixed64,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proof) Reset() {
	*x = Proof{}
	mi := &file_pensiero_v1_reasoning_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proof) ProtoMessage() {}

func (x *Proof) ProtoReflect() protoreflect.Message {
	mi := &file_pensiero_v1_reasoning_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proof.ProtoReflect.Descriptor instead.
func (*Proof) Descriptor() ([]byte, []int) {
	return file_pensiero_v1_reasoning_proto_rawDescGZIP(), []int{2}
}

func (x *Proof) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Proof) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Proof) GetPredicate() string {
	if x != nil {
		return x.Predicate
	}
	return ""
}

func (x *Proof) GetRuleClass() string {
	if x != nil {
		return x.RuleClass
	}
	return ""
}

func (x *Proof) GetSteps() []*ProofStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *Proof) GetHops() int32 {
	if x != nil {
		return x.Hops
	}
	return 0
}

func (x *Proof) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type EntailsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Claim *Claim                 `protobuf:"bytes,1,opt,name=claim,proto3" json:"claim,omitempty"`
	// assumed_facts are per-request ground facts (e.g. a patient's findings as
	// (finding, present, patient)) the conditional reasoner may use to satisfy rule
	// conditions for THIS request only — they are not written to the graph.
	AssumedFacts  []*Claim `protobuf:"bytes,2,rep,name=assumed_facts,json=assumedFacts,proto3" json:"assumed_facts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntailsRequest) Reset() {
	*x = EntailsRequest{}
	mi := &file_pensiero_v1_reasoning_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntailsRequest) ProtoMessage() {}

func (x *EntailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pensiero_v1_reasoning_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntailsRequest.ProtoReflect.Descriptor instead.
func (*EntailsRequest) Descriptor() ([]byte, []int) {
	return file_pensiero_v1_reasoning_proto_rawDescGZIP(), []int{3}
}

func (x *EntailsRequest) GetClaim() *Claim {
	if x != nil {
		return x.Claim
	}
	return nil
}

func (x *EntailsRequest) GetAssumedFacts() []*Claim {
	if x != nil {
		return x.AssumedFacts
	}
	return nil
}

type EntailResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Best          *Proof                 `protobuf:"bytes,1,opt,name=best,proto3" json:"best,omitempty"`       // nil when no proof
	Verdict       string                 `protobuf:"bytes,2,opt,name=verdict,proto3" json:"verdict,omitempty"` // "entailed" | "contradicted" | "unsupported"
	All           []*Proof               `protobuf:"bytes,3,rep,name=all,proto3" json:"all,omitempty"`
	Confidence    float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntailResult) Reset() {
	*x = EntailResult{}
	mi := &file_pensiero_v1_reasoning_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntailResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntailResult) ProtoMessage() {}

func (x *EntailResult) ProtoReflect() protoreflect.Message {
	mi := &file_pensiero_v1_reasoning_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntailResult.ProtoReflect.Descriptor instead.
func (*EntailResult) Descriptor() ([]byte, []int) {
	return file_pensiero_v1_reasoning_proto_rawDescGZIP(), []int{4}
}

func (x *EntailResult) GetBest() *Proof {
	if x != nil {
		return x.Best
	}
	return nil
}

func (x *EntailResult) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *EntailResult) GetAll() []*Proof {
	if x != nil {
		return x.All
	}
	return nil
}

func (x *EntailResult) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type ContradictsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claim         *Claim                 `protobuf:"bytes,1,opt,name=claim,proto3" json:"claim,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContradictsRequest) Reset() {
	*x = ContradictsRequest{}
	mi := &file_pensiero_v1_reasoning_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContradictsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContradictsRequest) ProtoMessage() {}

func (x *ContradictsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pensiero_v1_reasoning_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContradictsRequest.ProtoReflect.Descriptor instead.
func (*ContradictsRequest) Descriptor() ([]byte, []int) {
	return file_pensiero_v1_reasoning_proto_rawDescGZIP(), []int{5}
}

func (x *ContradictsRequest) GetClaim() *Claim {
	if x != nil {
		return x.Claim
	}
	return nil
}

type ContradictsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contradicts   bool                   `protobuf:"varint,1,opt,name=contradicts,proto3" json:"contradicts,omitempty"`
	Proof         *Proof                 `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"` // nil when no conflict
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContradictsResponse) Reset() {
	*x = ContradictsResponse{}
	mi := &file_pensiero_v1_reasoning_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContradictsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContradictsResponse) ProtoMessage() {}

func (x *ContradictsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pensiero_v1_reasoning_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContradictsResponse.ProtoReflect.Descriptor instead.
func (*ContradictsResponse) Descriptor() ([]byte, []int) {
	return file_pensiero_v1_reasoning_proto_rawDescGZIP(), []int{6}
}

func (x *ContradictsResponse) GetContradicts() bool {
	if x != nil {
		return x.Contradicts
	}
	return false
}

func (x *ContradictsResponse) GetProof() *Proof {
	if x != nil {
		return x.Proof
	}
	return nil
}

type DeriveRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Source         string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target         string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Preds          []string               `protobuf:"bytes,3,rep,name=preds,proto3" json:"preds,omitempty"`
	MaxHops        int32                  `protobuf:"varint,4,opt,name=max_hops,json=maxHops,proto3" json:"max_hops,omitempty"`
	Decay          float64                `protobuf:"fixed64,5,opt,name=decay,proto3" json:"decay,omitempty"`
	MinConf        float64                `protobuf:"fixed64,6,opt,name=min_conf,json=minConf,proto3" json:"min_conf,omitempty"`
	Limit          int32                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	IncludeInverse bool                   `protobuf:"varint,8,opt,name=include_inverse,json=includeInverse,proto3" json:"include_inverse,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeriveRequest) Reset() {
	*x = DeriveRequest{}
	mi := &file_pensiero_v1_reasoning_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeriveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeriveRequest) ProtoMessage() {}

func (x *DeriveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pensiero_v1_reasoning_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeriveRequest.ProtoReflect.Descriptor instead.
func (*DeriveRequest) Descriptor() ([]byte, []int) {
	return file_pensiero_v1_reasoning_proto_rawDescGZIP(), []int{7}
}

func (x *DeriveRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DeriveRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *DeriveRequest) GetPreds() []string {
	if x != nil {
		return x.Preds
	}
	return nil
}

func (x *DeriveRequest) GetMaxHops() int32 {
	if x != nil {
		return x.MaxHops
	}
	return 0
}

func (x *DeriveRequest) GetDecay() float64 {
	if x != nil {
		return x.Decay
	}
	return 0
}

func (x *DeriveRequest) GetMinConf() float64 {
	if x != nil {
		return x.MinConf
	}
	return 0
}

func (x *DeriveRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *DeriveRequest) GetIncludeInverse() bool {
	if x != nil {
		return x.IncludeInverse
	}
	return false
}

type DeriveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proofs        []*Proof               `protobuf:"bytes,1,rep,name=proofs,proto3" json:"proofs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeriveResponse) Reset() {
	*x = DeriveResponse{}
	mi := &file_pensiero_v1_reasoning_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeriveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeriveResponse) ProtoMessage() {}

func (x *DeriveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pensiero_v1_reasoning_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeriveResponse.ProtoReflect.Descriptor instead.
func (*DeriveResponse) Descriptor() ([]byte, []int) {
	return file_pensiero_v1_reasoning_proto_rawDescGZIP(), []int{8}
}

func (x *DeriveResponse) GetProofs() []*Proof {
	if x != nil {
		return x.Proofs
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_pensiero_v1_reasoning_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pensiero_v1_reasoning_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_pensiero_v1_reasoning_proto_rawDescGZIP(), []int{9}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_pensiero_v1_reasoning_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pensiero_v1_reasoning_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_pensiero_v1_reasoning_proto_rawDescGZIP(), []int{10}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_pensiero_v1_reasoning_proto protoreflect.FileDescriptor

const file_pensiero_v1_reasoning_proto_rawDesc = "" +
	"\n" +
	"\x1bpensiero/v1/reasoning.proto\x12\vpensiero.v1\"W\n" +
	"\x05Claim\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1c\n" +
	"\tpredicate\x18\x02 \x01(\tR\tpredicate\x12\x16\n" +
	"\x06object\x18\x03 \x01(\tR\x06object\"\xa6\x01\n" +
	"\tProofStep\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\x12\x12\n" +
	"\x04rule\x18\x02 \x01(\tR\x04rule\x12\x1c\n" +
	"\tpredicate\x18\x03 \x01(\tR\tpredicate\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x05 \x01(\tR\x06target\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x01R\n" +
	"confidence\"\xd6\x01\n" +
	"\x05Proof\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1c\n" +
	"\tpredicate\x18\x03 \x01(\tR\tpredicate\x12\x1d\n" +
	"\n" +
	"rule_class\x18\x04 \x01(\tR\truleClass\x12,\n" +
	"\x05steps\x18\x05 \x03(\v2\x16.pensiero.v1.ProofStepR\x05steps\x12\x12\n" +
	"\x04hops\x18\x06 \x01(\x05R\x04hops\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x01R\n" +
	"confidence\"s\n" +
	"\x0eEntailsRequest\x12(\n" +
	"\x05claim\x18\x01 \x01(\v2\x12.pensiero.v1.ClaimR\x05claim\x127\n" +
	"\rassumed_facts\x18\x02 \x03(\v2\x12.pensiero.v1.ClaimR\fassumedFacts\"\x96\x01\n" +
	"\fEntailResult\x12&\n" +
	"\x04best\x18\x01 \x01(\v2\x12.pensiero.v1.ProofR\x04best\x12\x18\n" +
	"\averdict\x18\x02 \x01(\tR\averdict\x12$\n" +
	"\x03all\x18\x03 \x03(\v2\x12.pensiero.v1.ProofR\x03all\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\">\n" +
	"\x12ContradictsRequest\x12(\n" +
	"\x05claim\x18\x01 \x01(\v2\x12.pensiero.v1.ClaimR\x05claim\"a\n" +
	"\x13ContradictsResponse\x12 \n" +
	"\vcontradicts\x18\x01 \x01(\bR\vcontradicts\x12(\n" +
	"\x05proof\x18\x02 \x01(\v2\x12.pensiero.v1.ProofR\x05proof\"\xe0\x01\n" +
	"\rDeriveRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x14\n" +
	"\x05preds\x18\x03 \x03(\tR\x05preds\x12\x19\n" +
	"\bmax_hops\x18\x04 \x01(\x05R\amaxHops\x12\x14\n" +
	"\x05decay\x18\x05 \x01(\x01R\x05decay\x12\x19\n" +
	"\bmin_conf\x18\x06 \x01(\x01R\aminConf\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\x12'\n" +
	"\x0finclude_inverse\x18\b \x01(\bR\x0eincludeInverse\"<\n" +
	"\x0eDeriveResponse\x12*\n" +
	"\x06proofs\x18\x01 \x03(\v2\x12.pensiero.v1.ProofR\x06proofs\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xac\x02\n" +
	"\x0fReasonerService\x12A\n" +
	"\aEntails\x12\x1b.pensiero.v1.EntailsRequest\x1a\x19.pensiero.v1.EntailResult\x12P\n" +
	"\vContradicts\x12\x1f.pensiero.v1.ContradictsRequest\x1a .pensiero.v1.ContradictsResponse\x12A\n" +
	"\x06Derive\x12\x1a.pensiero.v1.DeriveRequest\x1a\x1b.pensiero.v1.DeriveResponse\x12A\n" +
	"\x06Health\x12\x1a.pensiero.v1.HealthRequest\x1a\x1b.pensiero.v1.HealthResponseB7Z5github.com/soundprediction/pensiero/pkg/grpcsvc/pb;pbb\x06proto3"

var (
	file_pensiero_v1_reasoning_proto_rawDescOnce sync.Once
	file_pensiero_v1_reasoning_proto_rawDescData []byte
)

func file_pensiero_v1_reasoning_proto_rawDescGZIP() []byte {
	file_pensiero_v1_reasoning_proto_rawDescOnce.Do(func() {
		file_pensiero_v1_reasoning_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pensiero_v1_reasoning_proto_rawDesc), len(file_pensiero_v1_reasoning_proto_rawDesc)))
	})
	return file_pensiero_v1_reasoning_proto_rawDescData
}

var file_pensiero_v1_reasoning_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pensiero_v1_reasoning_proto_goTypes = []any{
	(*Claim)(nil),               // 0: pensiero.v1.Claim
	(*ProofStep)(nil),           // 1: pensiero.v1.ProofStep
	(*Proof)(nil),               // 2: pensiero.v1.Proof
	(*EntailsRequest)(nil),      // 3: pensiero.v1.EntailsRequest
	(*EntailResult)(nil),        // 4: pensiero.v1.EntailResult
	(*ContradictsRequest)(nil),  // 5: pensiero.v1.ContradictsRequest
	(*ContradictsResponse)(nil), // 6: pensiero.v1.ContradictsResponse
	(*DeriveRequest)(nil),       // 7: pensiero.v1.DeriveRequest
	(*DeriveResponse)(nil),      // 8: pensiero.v1.DeriveResponse
	(*HealthRequest)(nil),       // 9: pensiero.v1.HealthRequest
	(*HealthResponse)(nil),      // 10: pensiero.v1.HealthResponse
}
var file_pensiero_v1_reasoning_proto_depIdxs = []int32{
	1,  // 0: pensiero.v1.Proof.steps:type_name -> pensiero.v1.ProofStep
	0,  // 1: pensiero.v1.EntailsRequest.claim:type_name -> pensiero.v1.Claim
	0,  // 2: pensiero.v1.EntailsRequest.assumed_facts:type_name -> pensiero.v1.Claim
	2,  // 3: pensiero.v1.EntailResult.best:type_name -> pensiero.v1.Proof
	2,  // 4: pensiero.v1.EntailResult.all:type_name -> pensiero.v1.Proof
	0,  // 5: pensiero.v1.ContradictsRequest.claim:type_name -> pensiero.v1.Claim
	2,  // 6: pensiero.v1.ContradictsResponse.proof:type_name -> pensiero.v1.Proof
	2,  // 7: pensiero.v1.DeriveResponse.proofs:type_name -> pensiero.v1.Proof
	3,  // 8: pensiero.v1.ReasonerService.Entails:input_type -> pensiero.v1.EntailsRequest
	5,  // 9: pensiero.v1.ReasonerService.Contradicts:input_type -> pensiero.v1.ContradictsRequest
	7,  // 10: pensiero.v1.ReasonerService.Derive:input_type -> pensiero.v1.DeriveRequest
	9,  // 11: pensiero.v1.ReasonerService.Health:input_type -> pensiero.v1.HealthRequest
	4,  // 12: pensiero.v1.ReasonerService.Entails:output_type -> pensiero.v1.EntailResult
	6,  // 13: pensiero.v1.ReasonerService.Contradicts:output_type -> pensiero.v1.ContradictsResponse
	8,  // 14: pensiero.v1.ReasonerService.Derive:output_type -> pensiero.v1.DeriveResponse
	10, // 15: pensiero.v1.ReasonerService.Health:output_type -> pensiero.v1.HealthResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pensiero_v1_reasoning_proto_init() }
func file_pensiero_v1_reasoning_proto_init() {
	if File_pensiero_v1_reasoning_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pensiero_v1_reasoning_proto_rawDesc), len(file_pensiero_v1_reasoning_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pensiero_v1_reasoning_proto_goTypes,
		DependencyIndexes: file_pensiero_v1_reasoning_proto_depIdxs,
		MessageInfos:      file_pensiero_v1_reasoning_proto_msgTypes,
	}.Build()
	File_pensiero_v1_reasoning_proto = out.File
	file_pensiero_v1_reasoning_proto_goTypes = nil
	file_pensiero_v1_reasoning_proto_depIdxs = nil
}
